package com.orbyte.canvasstudio.drawing

import android.graphics.Bitmap
import android.graphics.Color
import java.util.UUID

enum class DrawingTool {
    BRUSH,
    ERASER,
    LINE,
    RECTANGLE,
    ELLIPSE,
    FILL,
    GRADIENT,
    SELECT_RECTANGLE,
    SELECT_ELLIPSE,
    SELECT_LASSO,
    TRANSFORM,
    EYEDROPPER,
    HAND,
}

enum class GuideMode {
    NONE,
    PERSPECTIVE_ONE_POINT,
    PERSPECTIVE_TWO_POINT,
}

enum class LayerBlendMode {
    NORMAL,
    MULTIPLY,
    SCREEN,
    OVERLAY,
    ADD,
    DARKEN,
    LIGHTEN,
}

enum class BrushKind {
    PENCIL,
    INK,
    MARKER,
    PAINT,
    AIRBRUSH,
    CHARCOAL,
    CHALK,
}

data class BrushPreset(
    val id: String,
    val name: String,
    val category: String,
    val kind: BrushKind,
    val sizePx: Float,
    val opacity: Float,
    val hardness: Float,
    val spacing: Float,
    val stabilization: Float,
    val flow: Float = 1f,
    val minSize: Float = 0.22f,
    val pressureSize: Boolean = true,
    val pressureOpacity: Boolean = false,
    val tiltResponse: Float = 0f,
    val taperStart: Float = 0.08f,
    val taperEnd: Float = 0.06f,
    val scatter: Float = 0f,
    val grain: Float = 0f,
    val velocitySize: Float = 0f,
)

data class BrushSettings(
    val sizePx: Float = 24f,
    val opacity: Float = 1f,
    val color: Int = Color.rgb(38, 42, 48),
    val hardness: Float = 0.85f,
    val spacing: Float = 0.12f,
    val stabilization: Float = 0.22f,
    val flow: Float = 1f,
    val minSize: Float = 0.22f,
    val pressureSize: Boolean = true,
    val pressureOpacity: Boolean = false,
    val tiltResponse: Float = 0f,
    val taperStart: Float = 0.08f,
    val taperEnd: Float = 0.06f,
    val scatter: Float = 0f,
    val grain: Float = 0f,
    val velocitySize: Float = 0f,
    val kind: BrushKind = BrushKind.PENCIL,
)

data class StrokePoint(
    val x: Float,
    val y: Float,
    val pressure: Float,
    val tilt: Float,
    val timestampMillis: Long,
)

sealed interface DrawCommand {
    val id: String
}

data class StrokeCommand(
    override val id: String = UUID.randomUUID().toString(),
    val points: List<StrokePoint>,
    val tool: DrawingTool,
    val settings: BrushSettings,
    val clipPoints: List<StrokePoint> = emptyList(),
) : DrawCommand

data class ShapeCommand(
    override val id: String = UUID.randomUUID().toString(),
    val tool: DrawingTool,
    val startX: Float,
    val startY: Float,
    val endX: Float,
    val endY: Float,
    val settings: BrushSettings,
    val clipPoints: List<StrokePoint> = emptyList(),
) : DrawCommand

data class GradientCommand(
    override val id: String = UUID.randomUUID().toString(),
    val startX: Float,
    val startY: Float,
    val endX: Float,
    val endY: Float,
    val startColor: Int,
    val endColor: Int,
    val clipPoints: List<StrokePoint> = emptyList(),
) : DrawCommand

/**
 * In-memory raster patch used by non-destructive fill and selection transforms.
 *
 * The bitmap is intentionally not serialized: project persistence stores the resulting raster
 * tiles. Keeping it as a command during the active session makes undo/redo deterministic.
 */
data class PixelPatchCommand(
    override val id: String = UUID.randomUUID().toString(),
    val bitmap: Bitmap,
    val left: Float,
    val top: Float,
) : DrawCommand

data class TransformSelectionCommand(
    override val id: String = UUID.randomUUID().toString(),
    val sourcePoints: List<StrokePoint>,
    val sourceBoundsLeft: Float,
    val sourceBoundsTop: Float,
    val sourceBoundsRight: Float,
    val sourceBoundsBottom: Float,
    val bitmap: Bitmap,
    val matrixValues: FloatArray,
) : DrawCommand

data class LayerUiModel(
    val id: String,
    val name: String,
    val visible: Boolean,
    val opacity: Float,
    val blendMode: LayerBlendMode,
    val alphaLocked: Boolean,
    val clipping: Boolean,
    val isActive: Boolean,
    val groupId: String? = null,
    val hasMask: Boolean = false,
    val maskEnabled: Boolean = true,
    val editingMask: Boolean = false,
)

data class LayerGroupUiModel(
    val id: String,
    val name: String,
    val visible: Boolean,
    val opacity: Float,
    val collapsed: Boolean,
    val layerCount: Int,
)

val premiumBrushes = listOf(
    BrushPreset(
        id = "pencil-hb",
        name = "Lápiz HB",
        category = "Lápices",
        kind = BrushKind.PENCIL,
        sizePx = 16f,
        opacity = 0.82f,
        hardness = 0.76f,
        spacing = 0.08f,
        stabilization = 0.2f,
        flow = 0.72f,
        minSize = 0.16f,
        pressureOpacity = true,
        tiltResponse = 0.42f,
        taperStart = 0.18f,
        taperEnd = 0.12f,
        grain = 0.22f,
        velocitySize = 0.12f,
    ),
    BrushPreset(
        id = "pencil-6b",
        name = "Lápiz 6B",
        category = "Lápices",
        kind = BrushKind.PENCIL,
        sizePx = 30f,
        opacity = 0.76f,
        hardness = 0.5f,
        spacing = 0.1f,
        stabilization = 0.14f,
        flow = 0.64f,
        minSize = 0.22f,
        pressureOpacity = true,
        tiltResponse = 0.72f,
        taperStart = 0.14f,
        taperEnd = 0.1f,
        grain = 0.36f,
        scatter = 0.05f,
    ),
    BrushPreset(
        id = "mechanical-pencil",
        name = "Portaminas",
        category = "Lápices",
        kind = BrushKind.PENCIL,
        sizePx = 8f,
        opacity = 0.92f,
        hardness = 0.92f,
        spacing = 0.05f,
        stabilization = 0.34f,
        flow = 0.88f,
        minSize = 0.34f,
        pressureOpacity = true,
        tiltResponse = 0.12f,
        taperStart = 0.1f,
        taperEnd = 0.08f,
        grain = 0.08f,
        velocitySize = 0.08f,
    ),
    BrushPreset(
        id = "technical-ink",
        name = "Tinta técnica",
        category = "Tinta",
        kind = BrushKind.INK,
        sizePx = 11f,
        opacity = 1f,
        hardness = 1f,
        spacing = 0.04f,
        stabilization = 0.48f,
        flow = 1f,
        minSize = 0.78f,
        pressureSize = false,
        taperStart = 0f,
        taperEnd = 0f,
    ),
    BrushPreset(
        id = "pressure-ink",
        name = "Tinta con presión",
        category = "Tinta",
        kind = BrushKind.INK,
        sizePx = 25f,
        opacity = 1f,
        hardness = 0.96f,
        spacing = 0.05f,
        stabilization = 0.36f,
        flow = 1f,
        minSize = 0.08f,
        taperStart = 0.24f,
        taperEnd = 0.2f,
        velocitySize = 0.18f,
    ),
    BrushPreset(
        id = "comic-nib",
        name = "Plumilla cómic",
        category = "Tinta",
        kind = BrushKind.INK,
        sizePx = 34f,
        opacity = 1f,
        hardness = 0.94f,
        spacing = 0.04f,
        stabilization = 0.3f,
        flow = 1f,
        minSize = 0.04f,
        tiltResponse = 0.18f,
        taperStart = 0.32f,
        taperEnd = 0.28f,
        velocitySize = 0.22f,
    ),
    BrushPreset(
        id = "marker",
        name = "Marcador",
        category = "Pintura",
        kind = BrushKind.MARKER,
        sizePx = 58f,
        opacity = 0.38f,
        hardness = 0.8f,
        spacing = 0.08f,
        stabilization = 0.12f,
        flow = 0.82f,
        minSize = 0.7f,
        pressureSize = false,
        pressureOpacity = true,
        tiltResponse = 0.28f,
        taperStart = 0f,
        taperEnd = 0f,
        grain = 0.1f,
    ),
    BrushPreset(
        id = "gouache",
        name = "Gouache opaco",
        category = "Pintura",
        kind = BrushKind.PAINT,
        sizePx = 72f,
        opacity = 0.88f,
        hardness = 0.76f,
        spacing = 0.07f,
        stabilization = 0.14f,
        flow = 0.82f,
        minSize = 0.26f,
        pressureOpacity = true,
        tiltResponse = 0.2f,
        taperStart = 0.08f,
        taperEnd = 0.08f,
        grain = 0.16f,
        scatter = 0.025f,
    ),
    BrushPreset(
        id = "soft-paint",
        name = "Pintura suave",
        category = "Pintura",
        kind = BrushKind.PAINT,
        sizePx = 84f,
        opacity = 0.5f,
        hardness = 0.34f,
        spacing = 0.08f,
        stabilization = 0.18f,
        flow = 0.58f,
        minSize = 0.3f,
        pressureOpacity = true,
        tiltResponse = 0.16f,
        taperStart = 0.06f,
        taperEnd = 0.06f,
        grain = 0.08f,
    ),
    BrushPreset(
        id = "airbrush",
        name = "Aerógrafo suave",
        category = "Aerógrafo",
        kind = BrushKind.AIRBRUSH,
        sizePx = 112f,
        opacity = 0.2f,
        hardness = 0.06f,
        spacing = 0.06f,
        stabilization = 0.1f,
        flow = 0.46f,
        minSize = 0.45f,
        pressureOpacity = true,
        taperStart = 0f,
        taperEnd = 0f,
        scatter = 0.04f,
    ),
    BrushPreset(
        id = "charcoal",
        name = "Carboncillo",
        category = "Textura",
        kind = BrushKind.CHARCOAL,
        sizePx = 46f,
        opacity = 0.68f,
        hardness = 0.3f,
        spacing = 0.1f,
        stabilization = 0.1f,
        flow = 0.62f,
        minSize = 0.24f,
        pressureOpacity = true,
        tiltResponse = 0.78f,
        taperStart = 0.08f,
        taperEnd = 0.08f,
        scatter = 0.34f,
        grain = 0.72f,
    ),
    BrushPreset(
        id = "chalk",
        name = "Tiza seca",
        category = "Textura",
        kind = BrushKind.CHALK,
        sizePx = 38f,
        opacity = 0.62f,
        hardness = 0.58f,
        spacing = 0.09f,
        stabilization = 0.08f,
        flow = 0.54f,
        minSize = 0.2f,
        pressureOpacity = true,
        tiltResponse = 0.5f,
        taperStart = 0.06f,
        taperEnd = 0.06f,
        scatter = 0.24f,
        grain = 0.62f,
    ),
)
